controller_list:
  - name: fake_left_leg_group_controller
    type: $(arg fake_execution_type)
    joints:
      - j_left_hip
      - j_left_upper_leg
      - j_left_lower_leg
      - j_left_foot
  - name: fake_right_leg_group_controller
    type: $(arg fake_execution_type)
    joints:
      - j_right_hip
      - j_right_upper_leg
      - j_right_lower_leg
      - j_right_foot
initial:  # Define initial robot poses per group
  - group: left_leg_group
    pose: zero_pose
  - group: right_leg_group
    pose: zero_pose